// src/pages/tutor/TutorDashboard.jsx
import { useEffect, useMemo } from "react";
import { Link, useNavigate } from "react-router-dom";

export default function TutorDashboard() {
  const navigate = useNavigate();

  // Load demo user from local/session storage (used for milestone demo only)
  const user = useMemo(() => {
    try {
      return JSON.parse(
        localStorage.getItem("demoUser") ||
          sessionStorage.getItem("demoUser") ||
          "null"
      );
    } catch {
      return null;
    }
  }, []);

  // Extract a display name from the email (before the @ symbol)
  const displayName = useMemo(() => {
    if (!user?.email) return "Tutor";
    const beforeAt = user.email.split("@")[0] || "Tutor";
    return beforeAt.charAt(0).toUpperCase() + beforeAt.slice(1);
  }, [user]);

  const card = "rounded-2xl border border-slate-300 bg-white p-6 shadow-sm";
  const bigTitle = "text-2xl md:text-3xl font-extrabold tracking-wide";

  // ===== Demo Data Below (Frontend only for milestone UI) =====
  // These will later be replaced by real API data when backend is implemented.

  // Upcoming tutoring sessions assigned to this tutor
  const upcomingSessions = [
    {
      id: 1,
      date: "Thu, Nov 28",
      time: "2:00 PM – 3:00 PM",
      student: "Brian Lee",
      course: "CSC 220 – Data Structures",
      mode: "Online",
    },
    {
      id: 2,
      date: "Fri, Nov 29",
      time: "10:00 AM – 11:00 AM",
      student: "Alice Chen",
      course: "CSC 210 – Intro to Programming",
      mode: "In-person",
    },
  ];

  // Recent activity generated by this tutor
  const recentActivity = [
    {
      id: 1,
      text: "Completed session with Daniel (CSC 415)",
      time: "2 hours ago",
    },
    {
      id: 2,
      text: "Received a new message from Alice",
      time: "Yesterday",
    },
    {
      id: 3,
      text: "Updated your tutor profile information",
      time: "2 days ago",
    },
  ];

  // Messages received from students (demo data)
  const messages = [
    {
      id: 1,
      student: "Alice Chen",
      snippet: "Hi, I need help with CSC 340 and some algorithm questions…",
      time: "2 hours ago",
      unread: true,
    },
    {
      id: 2,
      student: "Brian Wu",
      snippet: "Are you available next Monday afternoon?",
      time: "Yesterday",
      unread: false,
    },
    {
      id: 3,
      student: "Maya Patel",
      snippet: "Thank you for the last session, it really helped!",
      time: "2 days ago",
      unread: false,
    },
  ];

  // Redirect user to login page if no session is found
  useEffect(() => {
    if (!user) {
      const next = encodeURIComponent("/tutor/dashboard");
      navigate(`/login?next=${next}`, { replace: true });
    }
  }, [user, navigate]);

  return (
    <section className="space-y-6">
      {/* ===== Header Section ===== */}
      <div className={card}>
        <div className="flex items-start justify-between">
          {/* User greeting and avatar */}
          <div className="flex items-center gap-3">
            <div className="grid h-14 w-14 place-items-center rounded-full bg-slate-200 text-3xl text-slate-600">
              👤
            </div>
            <div>
              <div className="text-2xl font-extrabold">
                Welcome, {displayName}!
              </div>
            </div>
          </div>

          {/* Quick access icons */}
          <div className="flex items-center gap-4 text-2xl">
            <Link to="/inbox" title="Messages" className="hover:opacity-80">
              ✉️
            </Link>
            <Link to="/" title="Home" className="hover:opacity-80">
              🏠
            </Link>
          </div>
        </div>

        <h1 className={`mt-4 text-center ${bigTitle}`}>
          SFSU TUTORING PLATFORM
        </h1>
      </div>

      {/* ===== Profile Status Section (Required: must not be removed) ===== */}
      <div className={card}>
        <h2 className="text-lg md:text-xl font-extrabold">PROFILE STATUS</h2>

        <div className="mt-4 rounded-xl border border-slate-300 bg-slate-50 p-4">
          <div className="text-lg md:text-xl font-extrabold">
            YOU DON&apos;T HAVE A TUTOR PROFILE YET
          </div>

          <p className="mt-2 text-slate-800">
            Create your profile to start offering tutoring services.
          </p>

          <p className="mt-1 text-slate-800">
            <span className="underline underline-offset-2">
              Your profile will be reviewed by administrators
            </span>{" "}
            before appearing in search results.
          </p>

          <div className="mt-5">
            <button
              onClick={() => navigate("/tutor/posting")}
              className="rounded-md border px-5 py-2 font-semibold hover:bg-white"
            >
              CREATE PROFILE
            </button>
          </div>
        </div>
      </div>

      {/* ===== Upcoming Sessions Section ===== */}
      <div className={card}>
        <div className="flex items-center justify-between">
          <h2 className="text-lg md:text-xl font-extrabold">
            UPCOMING SESSIONS
          </h2>
          <span className="text-xs text-slate-500">
            {upcomingSessions.length} scheduled
          </span>
        </div>

        <div className="mt-4 space-y-3">
          {upcomingSessions.map((s) => (
            <div
              key={s.id}
              className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm"
            >
              {/* Session header */}
              <div className="flex items-center justify-between">
                <span className="font-semibold text-slate-900">
                  {s.student}
                </span>
                <span className="text-xs text-slate-600">{s.time}</span>
              </div>

              {/* Date & course */}
              <div className="mt-1 text-xs text-slate-700">
                {s.date} · {s.course}
              </div>

              {/* Mode badge */}
              <div className="mt-1">
                <span className="rounded-full bg-blue-100 px-2 py-0.5 text-[11px] font-semibold uppercase tracking-wide text-blue-700">
                  {s.mode}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ===== Recent Activity Section ===== */}
      <div className={card}>
        <div className="flex items-center justify-between">
          <h2 className="text-lg md:text-xl font-extrabold">
            RECENT ACTIVITY
          </h2>
          <span className="text-xs text-slate-500">
            Last {recentActivity.length} items
          </span>
        </div>

        <ol className="mt-3 space-y-2 text-sm">
          {recentActivity.map((item) => (
            <li
              key={item.id}
              className="flex items-start gap-2 border-l border-slate-300 pl-3"
            >
              {/* Activity bullet */}
              <span className="mt-1 h-2 w-2 rounded-full bg-blue-500" />
              <div>
                <p className="text-slate-900">{item.text}</p>
                <p className="text-xs text-slate-500">{item.time}</p>
              </div>
            </li>
          ))}
        </ol>
      </div>

      {/* ===== Messages Section (Messages received from students) ===== */}
      <div className={card}>
        <div className="flex items-center justify-between">
          <h2 className="text-lg md:text-xl font-extrabold">MESSAGES</h2>

          {/* Show unread count */}
          <span className="text-xs text-slate-500">
            {messages.filter((m) => m.unread).length} unread
          </span>
        </div>

        <div className="mt-4 space-y-3">
          {messages.map((msg) => (
            <button
              key={msg.id}
              type="button"
              className={`w-full rounded-xl border p-3 text-left text-sm transition hover:bg-slate-50 ${
                msg.unread
                  ? "border-blue-300 bg-blue-50"
                  : "border-slate-200 bg-white"
              }`}
            >
              {/* Message header */}
              <div className="flex items-center justify-between">
                <span className="font-semibold text-slate-900">
                  {msg.student}
                </span>
                <span className="text-xs text-slate-600">{msg.time}</span>
              </div>

              {/* Message snippet */}
              <p className="mt-1 line-clamp-2 text-xs text-slate-700">
                {msg.snippet}
              </p>

              {/* Unread badge */}
              {msg.unread && (
                <span className="mt-2 inline-flex rounded-full bg-blue-600 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-white">
                  NEW
                </span>
              )}
            </button>
          ))}
        </div>

        <p className="mt-3 text-[11px] text-slate-500">
          * These are demo messages for milestone UI. They can be replaced with
          real backend data later.
        </p>
      </div>
    </section>
  );
}
